
CREATE TABLE Carte 
    ( 
     autor        VARCHAR2 (50)  NOT NULL , 
     editura      VARCHAR2 (25)  NOT NULL , 
     isbn         VARCHAR2 (20)  NOT NULL , 
     an_publicare NUMBER (4) , 
     titlu        VARCHAR2 (50)  NOT NULL , 
     produs_id    NUMBER (5)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Carte 
    ADD 
    CHECK (REGEXP_LIKE(autor, '^[A-Za-z \-]{2,50}$')) 
;

ALTER TABLE Carte 
    ADD CONSTRAINT Carte_isbn_ck 
    CHECK (regexp_like(isbn, '^[0-9]{10,13}$')) 
;
CREATE UNIQUE INDEX Carte__IDX ON Carte 
    ( 
     produs_id ASC 
    ) 
    LOGGING 
;

ALTER TABLE Carte 
    ADD CONSTRAINT Carte_PK PRIMARY KEY ( produs_id ) ;

ALTER TABLE Carte 
    ADD CONSTRAINT Key_2 UNIQUE ( isbn ) ;

CREATE TABLE Client 
    ( 
     client_id NUMBER (5) GENERATED BY DEFAULT AS IDENTITY 
        ( START WITH 1 NOCACHE ORDER )  NOT NULL , 
     nume      VARCHAR2 (25)  NOT NULL , 
     email     VARCHAR2 (50)  NOT NULL , 
     telefon   VARCHAR2 (15) , 
     prenume   VARCHAR2 (25)  NOT NULL , 
     adresa    VARCHAR2 (150) 
    ) 
    LOGGING 
;

ALTER TABLE Client 
    ADD 
    CHECK (REGEXP_LIKE(nume, '^[A-Za-z ]{2,25}$')) 
;

ALTER TABLE Client 
    ADD CONSTRAINT Client_email_ck 
    CHECK (regexp_like(email,'[a-z0-9._%-]+@[a-z0-9._%-]+\.[a-z]{2,4}')) 
;

ALTER TABLE Client 
    ADD CONSTRAINT Client_telefon_ck 
    CHECK (regexp_like(telefon,'^[0-9+]+$')) 
;

ALTER TABLE Client 
    ADD 
    CHECK (REGEXP_LIKE(prenume, '^[A-Za-z ]{2,25}$')) 
;

ALTER TABLE Client 
    ADD 
    CHECK (REGEXP_LIKE(adresa, '^[A-Za-z0-9 ,.-]{5,150}$')) 
;

ALTER TABLE Client 
    ADD CONSTRAINT Client_PK PRIMARY KEY ( client_id ) ;

ALTER TABLE Client 
    ADD CONSTRAINT Key_2v2 UNIQUE ( email ) ;

CREATE TABLE Comanda 
    ( 
     comanda_id   NUMBER (5) GENERATED BY DEFAULT AS IDENTITY 
        ( START WITH 1 NOCACHE ORDER )  NOT NULL , 
     data_comanda DATE  NOT NULL , 
     status       VARCHAR2 (25)  NOT NULL , 
     client_id    NUMBER (5)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Comanda 
    ADD CONSTRAINT Comanda_status_ck 
    CHECK (status IN ('anulata', 'in curs de livrare', 'livrata', 'plasata')) 
;

ALTER TABLE Comanda 
    ADD CONSTRAINT Comanda_PK PRIMARY KEY ( comanda_id ) ;

CREATE TABLE Detalii_comanda 
    ( 
     detalii_id NUMBER (5) GENERATED BY DEFAULT AS IDENTITY 
        ( START WITH 1 NOCACHE ORDER )  NOT NULL , 
     cantitate  NUMBER (4)  NOT NULL , 
     comanda_id NUMBER (5)  NOT NULL , 
     produs_id  NUMBER (5)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Detalii_comanda 
    ADD CONSTRAINT Detalii_comanda_cantitate_ck 
    CHECK (cantitate>0) 
;

ALTER TABLE Detalii_comanda 
    ADD CONSTRAINT Detalii_comanda_PK PRIMARY KEY ( detalii_id ) ;

CREATE TABLE Feedback 
    ( 
     feedback_id   NUMBER (5) GENERATED BY DEFAULT AS IDENTITY 
        ( START WITH 1 NOCACHE ORDER )  NOT NULL , 
     stele         NUMBER (1)  NOT NULL , 
     comentariu    VARCHAR2 (100) , 
     data_feedback DATE  NOT NULL , 
     client_id     NUMBER (5)  NOT NULL , 
     produs_id     NUMBER (5)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Feedback 
    ADD CONSTRAINT Feedback_stele_ck 
    CHECK (stele BETWEEN 1 AND 5) 
;

ALTER TABLE Feedback 
    ADD CONSTRAINT Feedback_PK PRIMARY KEY ( feedback_id ) ;

CREATE TABLE Furnizor 
    ( 
     furnizor_id NUMBER (5) GENERATED BY DEFAULT AS IDENTITY 
        ( START WITH 1 NOCACHE ORDER )  NOT NULL , 
     nume_firma  VARCHAR2 (50)  NOT NULL , 
     cui         VARCHAR2 (10)  NOT NULL , 
     telefon     VARCHAR2 (15)  NOT NULL , 
     tara        VARCHAR2 (50) , 
     email       VARCHAR2 (50)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Furnizor 
    ADD 
    CHECK (REGEXP_LIKE(nume_firma, '^[A-Za-z ]{2,50}$')) 
;

ALTER TABLE Furnizor 
    ADD CONSTRAINT Furnizor_telefon_ck 
    CHECK (regexp_like(telefon,'^[0-9+]+$')) 
;

ALTER TABLE Furnizor 
    ADD 
    CHECK (REGEXP_LIKE(tara, '^[A-Za-z ]{5,50}$')) 
;

ALTER TABLE Furnizor 
    ADD CONSTRAINT Furnizor_email_ck 
    CHECK (regexp_like(email,'[a-z0-9._%-]+@[a-z0-9._%-]+\.[a-z]{2,4}')) 
;

ALTER TABLE Furnizor 
    ADD CONSTRAINT Furnizor_PK PRIMARY KEY ( furnizor_id ) ;

ALTER TABLE Furnizor 
    ADD CONSTRAINT Key_2v3 UNIQUE ( cui , email , telefon ) ;

CREATE TABLE Produs 
    ( 
     produs_id     NUMBER (5) GENERATED BY DEFAULT AS IDENTITY 
        ( START WITH 1 NOCACHE ORDER )  NOT NULL , 
     denumire      VARCHAR2 (50)  NOT NULL , 
     pret          NUMBER (3)  NOT NULL , 
     stoc          NUMBER (4)  NOT NULL , 
     descriere     VARCHAR2 (100) , 
     tip_produs_id NUMBER (5)  NOT NULL , 
     furnizor_id   NUMBER (5)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Produs 
    ADD 
    CHECK (REGEXP_LIKE(denumire, '^[A-Za-z ]{2,50}$')) 
;

ALTER TABLE Produs 
    ADD CONSTRAINT Produs_pret_ck 
    CHECK (pret>0) 
;

ALTER TABLE Produs 
    ADD CONSTRAINT Produs_stoc_ck 
    CHECK (stoc>=0) 
;

ALTER TABLE Produs 
    ADD CONSTRAINT Produs_PK PRIMARY KEY ( produs_id ) ;

CREATE TABLE Tip_produs 
    ( 
     tip_produs_id NUMBER (5) GENERATED BY DEFAULT AS IDENTITY 
        ( START WITH 1 NOCACHE ORDER )  NOT NULL , 
     denumire_tip  VARCHAR2 (50)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Tip_produs 
    ADD 
    CHECK (REGEXP_LIKE(denumire_tip, '^[A-Za-z ]{2,50}$')) 
;

ALTER TABLE Tip_produs 
    ADD CONSTRAINT Tip_produs_PK PRIMARY KEY ( tip_produs_id ) ;

ALTER TABLE Tip_produs 
    ADD CONSTRAINT Key_2v4 UNIQUE ( denumire_tip ) ;

ALTER TABLE Carte 
    ADD CONSTRAINT Carte_fk FOREIGN KEY 
    ( 
     produs_id
    ) 
    REFERENCES Produs 
    ( 
     produs_id
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Comanda 
    ADD CONSTRAINT Comanda_fk FOREIGN KEY 
    ( 
     client_id
    ) 
    REFERENCES Client 
    ( 
     client_id
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Detalii_comanda 
    ADD CONSTRAINT Detalii_comanda_fk FOREIGN KEY 
    ( 
     comanda_id
    ) 
    REFERENCES Comanda 
    ( 
     comanda_id
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Detalii_comanda 
    ADD CONSTRAINT Detalii_comanda_fkv2 FOREIGN KEY 
    ( 
     produs_id
    ) 
    REFERENCES Produs 
    ( 
     produs_id
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Feedback 
    ADD CONSTRAINT Feedback_fk FOREIGN KEY 
    ( 
     client_id
    ) 
    REFERENCES Client 
    ( 
     client_id
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Feedback 
    ADD CONSTRAINT Feedback_fkv2 FOREIGN KEY 
    ( 
     produs_id
    ) 
    REFERENCES Produs 
    ( 
     produs_id
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Produs 
    ADD CONSTRAINT Produs_fk FOREIGN KEY 
    ( 
     furnizor_id
    ) 
    REFERENCES Furnizor 
    ( 
     furnizor_id
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Produs 
    ADD CONSTRAINT Produs_fkv2 FOREIGN KEY 
    ( 
     tip_produs_id
    ) 
    REFERENCES Tip_produs 
    ( 
     tip_produs_id
    ) 
    NOT DEFERRABLE 
;

CREATE OR REPLACE TRIGGER trg_Comanda_BRIU 
    BEFORE INSERT OR UPDATE ON Comanda 
    FOR EACH ROW 
BEGIN
	IF(:new.data_comanda>SYSDATE)
	THEN
        RAISE_APPLICATION_ERROR( -20001,
        'Data invalida: ' || TO_CHAR( :new.data_comanda, 'DD.MM.YYYY HH24:MI:SS' ) || ' trebuie sa fie mai mica decat data curenta.' );
    	END IF;
END; 
/

CREATE OR REPLACE TRIGGER trg_Feedback_BRIU 
    BEFORE INSERT OR UPDATE ON Feedback 
    FOR EACH ROW 
BEGIN
	IF(:new.data_feedback>SYSDATE)
	THEN
        RAISE_APPLICATION_ERROR( -20001,
        'Data invalida: ' || TO_CHAR( :new.data_feedback, 'DD.MM.YYYY HH24:MI:SS' ) || ' trebuie sa fie mai mica decat data curenta.' );
    	END IF;
END; 
/



